use_default_settings: true

general:
  debug: false
  instance_name: "FRIDAY Search"
  privacypolicy_url: ""
  donation_url: ""
  contact_url: ""
  enable_metrics: false

brand:
  new_issue_url: ""
  docs_url: ""
  public_instances: ""
  wiki_url: ""

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "${SEARXNG_SECRET}"
  base_url: "http://localhost:8081/"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
  default_theme: simple

outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

enabled_plugins:
  - "Hash plugin"
  - "Self Information"
  - "Tracker URL remover"
  - "Unit converter plugin"

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
